#!/bin/bash
git add . #tiek pieteiktas adreses "uzmanīšanai"
git config --global user.name lenardsk
git config --global user.email lenardskarklins64@gmail.com
git commit -m "Class_04"
git push origin main
